# Browse Books as any user
GET http://localhost:4004/browse/Books?
  # &$select=title,stock
  # &$expand=currency
  # &sap-language=de

# Browse Authors as any user
###
GET http://localhost:4004/browse/Authors/?
  &$expand=books($expand=currency)

### ------------------------------------------------------------------------
# Create book
POST http://localhost:4004/admin/Books
Content-Type: application/json;IEEE754Compatible=true
Authorization: Basic alice:

{
  "ID": 2,
  "title": "Poems : Pocket Poets",
  "descr": "The Everyman's Library Pocket Poets hardcover series is popular for its compact size and reasonable price which does not compromise content. Poems: Bronte contains poems that demonstrate a sensibility elemental in its force with an imaginative discipline and flexibility of the highest order. Also included are an Editor's Note and an index of first lines.",
  "author": { "ID": 101 },
  "stock": 5,
  "price": "12.05",
  "currency_code": "USD"
}

### -------------------------------------------------------------------------
# Browse Books as any user
GET http://localhost:4004/browse/Books?
   &$filter=ID eq 2

